#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "Need sudo later in script, enter now"
sudo echo ""

topgrade --disable emacs system

if [[ $(uname -s) == "Darwin" ]] && command -v "port"; then
	sudo port selfupdate
	sudo port upgrade outdated
fi

if [[ -d "$HOME"/.emacs.d ]]; then
	pushd "$HOME"/.emacs.d
	git fetch
	git pull --rebase
	if [[ -d "$HOME"/.doom.d ]]; then
		yes | ./bin/doom upgrade
		yes | ./bin/doom refresh
	fi
	popd
fi

