#!/usr/bin/env bash

print_files=("$@")
rsync -azvq "${print_files[@]}" printer:~/to_print
# ssh printer /bin/zsh <<EOF
# print_commands=()
# for doc in "${print_files[@]}"; do
# 	print_commands+=(lpr -P las2052 \'"${doc}"\' '\n')
# done
for doc in "${print_files[@]}"; do
	echo lpr -P las2052 "~/to_print/\"${doc}\""
done | ssh printer /bin/bash
