#!/usr/bin/env bash

DEST="$1"

if [ -z "$DEST" ]; then exit 1; fi

watchman-wait --max-events 0 . |
	# cat
	while read -r file; do
		if git check-ignore "$file"; then
			echo "$file is ignored"
		else
			echo "$file"
			rsync -azvq \
				"$file" "${DEST}"/"$file"
			echo -n 'Completed at '
			date
		fi
	done
